// src/app/board/board.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Notero } from '../services/notero.data-object';
import { INote, INoteWithVotes, IUser } from '../shared/interfaces';

@Component({
  selector: 'app-board',
  template: `
    <div class="board">
      <div *ngFor="let note of notes">
        <app-note
          [note]="note"
          [count]="note.votes"
          [user]="user"
          [highlightMine]="highlightMine"
          (click)="vote(note)"></app-note>
      </div>
    </div>
  `
})
export class BoardComponent implements OnInit {

  @Input() model: Notero;
  @Input() notes: INoteWithVotes[];
  @Input() user: IUser;
  @Input() highlightMine: any;

  constructor() { }

  ngOnInit() { }

  vote(note: INote) {
    this.model.vote(note);
  }

}

// src/partials/Board.tsx
import React, { FC } from 'react';
import { Note } from './Note';
import { INote, IUser } from '../models/interfaces';

interface BoardProps {
  notes: INote[];
  vote: (note: INote) => void;
  user: IUser;
  highlightMine: boolean;
}

export const Board: FC<BoardProps> = (props) => (
  <div className="board">
    {props.notes.map((note) => (
      <Note
        key={note.id}
        note={note}
        onClick={() => props.vote(note)}
        count={note.votes}
        user={props.user}
        highlightMine={props.highlightMine}
      />
    ))}
  </div>
);
